language: python
python:
    - 2.7
    - pypy
    - 3.3
    - 3.4
    - 3.5
    - 3.6
    - nightly
    - pypy3
sudo: false
matrix:
    fast_finish: true

install: make clean build/venv
script: make lint test